
env:
  - NODE_ENV=production

branches:
  only:
    - master

before_script:
  - npm i html-webpack-plugin --save-dev
  - npm install -g webpack
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token 1/X7bTY4KatyuB9Mr-ZCxyCQ68Cinxhyz92bzgdE1ZchcAdkYvXgLQLqIKAZLbvp3L
