
branches:
  only:
    - master

before_script:
  - npm install -g webpack
  - npm install -g html-webpack-plugin
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token 1/X7bTY4KatyuB9Mr-ZCxyCQ68Cinxhyz92bzgdE1ZchcAdkYvXgLQLqIKAZLbvp3L
